### ISSUE TITLE
[REQ] code llama2

### ISSUE THREAD

**Issue by c-nv-s** [sozercan/aikit#123]
### What kind of request is this?

Other

### What is your request or suggestion?

pretty new to this and was just wondering how I could serve this locally
https://huggingface.co/TheBloke/CodeLlama-7B-Instruct-GGUF/resolve/main/codellama-7b-instruct.Q5_K_M.gguf
???

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by c-nv-s** [comment]
nevermind should have read the docs

**Comment by sozercan** [comment]
@c-nv-s please refer to https://sozercan.github.io/aikit/create-images for creating new images
feel free to open an issue if any docs need clarification

**Comment by sozercan** [comment]
@c-nv-s please feel free to open a new issue with this and post your environment details and logs
