### ISSUE TITLE
[REQ] Add support for phi-3 mini model

### ISSUE THREAD

**Issue by surenderssm** [sozercan/aikit#209]
### What kind of request is this?

New feature

### What is your request or suggestion?

I would like to add a support for phi-3 mini model.

https://huggingface.co/microsoft/Phi-3-mini-128k-instruct

I am very new to this ecosystem, however I have a strong desire to learn and contribute in this space, pointers or references will be enough for me to get started. Let me know your thoughts!

### Are you willing to submit PRs to contribute to this feature request?

- [X] Yes, I am willing to implement it.

**Comment by sozercan** [comment]
Looks like llama.cpp doesn't support 128k due to longrope scaling type: https://github.com/ggerganov/llama.cpp/issues/6849

**Comment by sozercan** [comment]
Looks like https://github.com/ggerganov/llama.cpp/pull/7225 added support for 128k version. aikit v0.9.0 includes the llama.cpp version that has this.
