### ISSUE TITLE
Please add a code completion model?

### ISSUE THREAD

**Issue by ilyanoskov** [sozercan/aikit#236]
Hello, @sozercan! Big thanks for this amazing project.

Could you please add a code completion model too? Something like deepseek-coder. 

I tried packaging one myself with aikit but I am currently having network issues with ghcr and cannot do it myself. 

Thank you very much in advance

**Comment by sozercan** [comment]
@ilyanoskov I'll look into adding one. 

By the way, you don't need GHCR access specifically, aikit works with any local or remote container registries.

**Comment by ilyanoskov** [comment]
@sozercan thanks a lot! Perhaps Codestral, the newest model from Mistral can be the most interesting here.

**Comment by sozercan** [comment]
yea, that's what i was thinking too!

**Comment by sozercan** [comment]
@ilyanoskov codestral is now available: https://sozercan.github.io/aikit/docs/premade-models
