### ISSUE TITLE
[REQ] arm support

### ISSUE THREAD

**Issue by renatokeys** [sozercan/aikit#67]
### What kind of request is this?

Improvement of existing experience

### What is your request or suggestion?

<img width="581" alt="image" src="https://github.com/sozercan/aikit/assets/6384274/492402cc-05c4-4ebc-bd75-7f59c98c2a5f">
this occour when trying to use with arm 

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by sozercan** [comment]
@renatokeys thanks for opening an issue! this is blocked by https://github.com/mudler/LocalAI/issues/1249
